version: '3.6'

services:

  web:
    build:
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    networks:
      - dmz
    labels:
      - traefik.enable=true
      - traefik.http.routers.your-ip.entrypoints=websecure
      - traefik.http.routers.your-ip.rule=Host(`vysvedceni.zschyne.cz`)
      - traefik.http.services.hello.loadbalancer.server.port=3000

networks:
  dmz:
    driver: overlay
    external: true
