version: '3.6'

services:

  web:
    build:
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    ports:
      - "80:3001"
    networks:
      - dmz
    labels:
      - traefik.enable=true
      - traefik.http.routers.vysvedceni.entrypoints=websecure
      - traefik.http.routers.vysvedceni.rule=Host(`vysvedceni.zschyne.cz`)

networks:
  dmz:
    driver: overlay
    external: true
